/**
 * As 21 linhas da tabela de bônus de **Formação** (`docs/core/sistema-v4.1.0.md` — "⬡ Identidade"
 * > "⬦ Origem" > "⬦ Formação"), agrupadas em Combate (5), Movimento (2), Perícia (4), Equipamento (7)
 * e Logística (3). Conteúdo de JSONB `ficha.dados` — sem tabela `tipo_*` (§10.3). Cada código indexa
 * uma entrada de `FORMACOES` (`shared/regras/identidade`) com o efeito mecânico correspondente.
 *
 * O documento autoriza bônus fora desta lista ("autorizados pelo Mestre") — nesse caso
 * `FichaFormacaoDto.bonus` é `null` e só o `texto` livre é exibido (m3-23).
 */
export enum FormacaoBonusEnum {
  COMBATE_DADO_CATEGORIA_ARMA = 'COMBATE_DADO_CATEGORIA_ARMA',
  COMBATE_ESQUIVA_OU_BLOQUEIO = 'COMBATE_ESQUIVA_OU_BLOQUEIO',
  COMBATE_DANO_CORPO = 'COMBATE_DANO_CORPO',
  COMBATE_RESISTENCIA_TIPO_DANO = 'COMBATE_RESISTENCIA_TIPO_DANO',
  COMBATE_DANO_FURTIVO_DADO = 'COMBATE_DANO_FURTIVO_DADO',
  MOVIMENTO_DESLOCAMENTO = 'MOVIMENTO_DESLOCAMENTO',
  MOVIMENTO_DADO_CORRIDA = 'MOVIMENTO_DADO_CORRIDA',
  PERICIA_DADO_ATRIBUTO = 'PERICIA_DADO_ATRIBUTO',
  PERICIA_BONUS_ATRIBUTO = 'PERICIA_BONUS_ATRIBUTO',
  PERICIA_DADO_ATRIBUTO_CONDICAO = 'PERICIA_DADO_ATRIBUTO_CONDICAO',
  PERICIA_DADO_INICIATIVA = 'PERICIA_DADO_INICIATIVA',
  EQUIPAMENTO_DADO_ITENS_MEDICINAIS = 'EQUIPAMENTO_DADO_ITENS_MEDICINAIS',
  EQUIPAMENTO_BONUS_ITENS_MEDICINAIS = 'EQUIPAMENTO_BONUS_ITENS_MEDICINAIS',
  EQUIPAMENTO_DADO_EFEITO_ITENS_MEDICINAIS = 'EQUIPAMENTO_DADO_EFEITO_ITENS_MEDICINAIS',
  EQUIPAMENTO_DADO_ITENS_OPERACIONAIS = 'EQUIPAMENTO_DADO_ITENS_OPERACIONAIS',
  EQUIPAMENTO_BONUS_ITENS_OPERACIONAIS = 'EQUIPAMENTO_BONUS_ITENS_OPERACIONAIS',
  EQUIPAMENTO_DADO_EFEITO_ITENS_OPERACIONAIS = 'EQUIPAMENTO_DADO_EFEITO_ITENS_OPERACIONAIS',
  EQUIPAMENTO_TURNO_EXTRA_STATUS = 'EQUIPAMENTO_TURNO_EXTRA_STATUS',
  LOGISTICA_INVENTARIO_MAXIMO = 'LOGISTICA_INVENTARIO_MAXIMO',
  LOGISTICA_SOBRECARGA = 'LOGISTICA_SOBRECARGA',
  LOGISTICA_DT_REPARO = 'LOGISTICA_DT_REPARO',
}
